# -*- coding: utf-8 -*-
"""hello world_github.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15tFc89e_uyw6MnTb1TJdgnkN0OJFl-yy
"""

print("hello world")